[tool.poetry]
name = "miose-toolkit-llm"
version = "0.0.1"
description = "Miose Toolkit 大语言模型模块"
authors = ["KroMiose <li_xiangff@163.com>"]
packages = [{ include = "miose_toolkit_llm", from = "src" }]

[tool.poetry.dependencies]
python = ">=3.8, <3.12"
openai = { version = ">=0.27.0, <2.0.0", optional = true }
tiktoken = { version = ">=0.6.0, <1.0.0", optional = true }

[tool.poetry.extras]
openai = ["openai"]
tiktoken = ["tiktoken"]
all = ["openai", "tiktoken"]

[tool.poetry.scripts]
test = "src.tests:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
